pipeline {
    agent any

    tools {
        // Vérifiez bien que vous avez appelé votre outil 'node' dans Jenkins > Tools
        nodejs 'node' 
    }

    stages {
        stage('Installation des dépendances') {
            steps {
                // On entre dans les sous-dossiers avant de lancer npm install
                dir('Desktop/calculatrice-jenkins') {
                    bat 'npm install'
                }
            }
        }
        stage('Build manuel') {
            steps {
                dir('Desktop/calculatrice-jenkins') {
                    echo 'Construction de l\'application...'
                    bat 'dir'
                }
            }
        }
    }
}