pipeline {
    agent any

    tools {
        // Doit correspondre au nom configuré dans Administrer Jenkins > Tools
        nodejs 'node' 
    }

    stages {
        stage('Installation des dépendances') {
            steps {
                dir('Desktop/calculatrice-jenkins') {
                    // Installe Express, Jest et Supertest
                    bat 'npm install'
                }
            }
        }

        stage('Test Automatique') { 
            steps {
                dir('Desktop/calculatrice-jenkins') {
                    echo 'Exécution des tests unitaires...'
                    // Lance la commande "npm test" définie dans package.json
                    bat 'npm test'
                }
            }
        }

        stage('Build manuel') {
            steps {
                dir('Desktop/calculatrice-jenkins') {
                    echo 'Construction terminée avec succès !'
                    bat 'dir'
                }
            }
        }
    }
}